### PR TITLE
Updated to add the disable_validation Option. Speeds up repeatative r…

### PR DESCRIPTION
**Pull request by dancingcactus**
This is a feature that @adibbehjat and I have been debating to disable the validation options for requests.

### CODE REVIEW

**Comment by adibbehjat** [comment]
Excellent solution! Much better than what I originally had.

**Comment by adibbehjat** [comment]
Hey Justin!
I was wondering if your edition was merged to the master (versus mine).
Best,

**Comment by dancingcactus** [comment]
You are so right. I'll get it roled back and get this one merged. Sorry about that.

**Comment by dancingcactus** [comment]
All right the right branch has now been merged. Thanks for catching me on that one.

**Pull request merged**
