### PR TITLE
Streamline querying by minimizing number of calls in accounts.py

### PR DESCRIPTION
**Pull request by adibbehjat**
My commit aims to minimize API calls by creating a group of local files (tagged by date) that contains all the essential information (list of report suites, elements, metrics and segments). The benefit of this approach is that it minimizes the number calls when doing multiple requests through a loop. The files are updated daily in order to capture all the latest edits and changes in the system.

A good future plan is if there is a way to allow the user to delete all '.txt' files within the omniture folder if they wish to collect the latest information without waiting another day or deleting files manually.

### CODE REVIEW

**Comment by dancingcactus** [comment]
I really, really like this idea. I can definitely see how it would be useful especially if you are pulling the same things day after day or doing a bunch of pulls across different report suites. I want to get this  merged, but I have to be careful of existing implementations that aren't expecting this functionality. Thinking about this I wonder if we could make an option on the authenticate method to cache requests. 

Something like this
```python
omniture.authenticate(username,secret, cache=True)
```
That way users could select whether they want the caching to be enabled or not. We might even allow them to set their own cache key. 

Then we could create a method call `request_cached` so that the caching logic is in one place and doesn't have to be duplicated. 

Something like this. 

```python
    def request_cached(self, api, method, query={}, cache_key=None)
        if cache_key:
            key = cache_key
        else:
            key = self.cache_key
        
        #Generate a shortened hash of the query string so that different calls to the same method don't collide
        query_hash = base64.urlsafe_b64encode(hashlib.md5(query).digest())
        
        try:
            with open(self.file_path+'/data_'+api+'_'+method+'_'+query_hash+'_'+key+'.txt') as fp:
                for line in fp:
                    if line:
                        data = ast.literal_eval(line)
        
        except IOError as e:
            data = self.request(api, method, query)
            
            # Capture all other old text files
            filelist = [f for f in os.listdir(self.file_path) if f.startswith('data_'+api+'_'+method)]

            # Delete them
            for f in filelist:
                os.remove(self.file_path+'/'+f)

            # Build the new data
            the_file = open(self.file_path+'/data_'+api+'_'+method+'_'+query_hash+'_'+key+'.txt', 'w')
            the_file.write(str(data))
            the_file.close()
```

Then finally we just adjust the places where we call request to get the segments, metrics, and dimensions to call the request_cached if the cache setting is on. 

Thoughts?

**Comment by adibbehjat** [comment]
The caching method you provided is a good idea, but I think there may be a potential flaw in it. Here's the scenario:

I enable cache, conduct my query and report, and so my cached query is saved somewhere. Later, I disable the cache and work on different requests. Assuming in this period I added new segments or metric that aren't present within the saved cache. If I were to enable cache again, it'll fail as the cache of "Get Segment" that is present in my computer contains an older list of segments versus the new one.

The ideal method method, it seems, is to activate caching by generating a new cache file (only once) on instances of error only. In other words, instead of terminating the report, it'll re-do the report once again after the cache is updated. The challenge is 'saving' the number of times a cache is made in a span of time to avoid an infinite loop. In other words, finding a way to distinguish between a 'valid' entry versus a 'bad' entry: i.e. if someone enters a segment that doesn't exist in Adobe, then the system would loop forever and create caches.

I think merging the two methods (my caching method and your caching method), which is the combination of time-based caching and report-based caching, may be a good start. And the 'try' method will search only for "Get Segment", "Get Metrics", or "Get Elements" as triggers to whether to create a new cache or old one (otherwise, if we base it on unique reports, it'll delete the saved cache every time because it cannot find the report I want).

**Comment by dancingcactus** [comment]
That is a good point on the flaw. Good catch!

If we set the cache key to the current day by default would that effectively combine the two methods? 

I am not sure I follow your second paragraph? Are you saying that we would only generate regenerate cache file when a report generates an error (Like segment doesn't exist). Wouldn't that make it difficult to discover new segments/metrics/elements via the API since you would always be looking at a cached version. Or in other words you would never see new segments created when you run until you try to run a report that errors? 

I agree with your third point by default we would only want to cache the results of Get Segments, Get Elements, Get Metrics types of calls, I would also add the Get Report suites calls in there. I can see some cases where you would want to cache the results of a report. E.g. you have a web service that powers a dashboard and you don't want multiple instances of the dashboard making the same expensive call over and over. However, I think that is a very distant edge case :-). 

What if we changed the calls to the various get functions from this. 
```python
data = self.request_cached('Company', 'GetReportSuites')['report_suites']
```
to something like this
```python
if self.cache:
            data = self.request_cached('Company', 'GetReportSuites')['report_suites']
        else:
            data = self.request('Company', 'GetReportSuites')['report_suites']
```
That way they are cached (when caching is on) 

Thoughts?

**Comment by dancingcactus** [comment]
One more thing that might be relevant. The calls that get the ReportSuites/Metrics/Segments and Dimensions do use the memoize decorator so they are cached in memory assuming you use the same object. E.g. in this example there would only be one call to get the segments. 

```python
an = omniture.authenticate(username,secret)
suite = an.suites['somesuite']
suite.report.metric('pageviews').run()
suite.report.metric('visits').run()
```

I still really like the idea of being able to cache those calls and I think we should it just thought that might be helpful context.

**Comment by adibbehjat** [comment]
That's correct. If we're focused on a specific report suite, the segment, metric and element calls happen only once. 

But in my case, there are instances where I go through different report suites (for example, at my office we have report suites for each country (uscomp, ukcomp, cacomp, etc), and when we wish to explore mobile usage for different countries, I loop through the different report suites. Due to this nature, the request call for segment, metric and element is made for every country. The running time was literally 1-2 mins per country (assuming it's a light request), and there were 93 countries to parse through. The total time was around 1-1.5 hours for the system to parse through. 

Through my mechanism, I shrunk this down to 20 minutes, but I think I can go faster :wink:

You're correct in regards to my point that the segment cache will only be updated on instances of error. That may lead to one request being slow, but it'll save time for the subsequent requests.

**Comment by dancingcactus** [comment]
Very helpful. Maybe we should we instead allow for an option to disable the look up of the metrics, dimensions and segments? The only reason for it is to allow make it easier for users who are doing interactive scripting and to allow them to use segment/metric and element names instead of the IDs. Would that make more sense?

**Comment by adibbehjat** [comment]
That's a very good alternative to simply switch off the search lookup. Simplifies things a lot. In terms of what you shared in regards to IDs. Here's an example query for page lookup:

```python
report = suite.report.element('page').metric('visits').range(dateFrom, dateTo).filter(element='evar54',selected=[url])
```
In this simple example, you're stating that people would have to place the "ID" term for element, metric and within the filter, correct?

I assume for my case, I'm already using a simple ID called visits, but let's say if I wanted to find the "Gallery Interaction Rate" metrics, I need to set the id of `cm300000899_557f46ece4b0d23197c999ca`. Is that the solution you're suggesting (can we run a report without the Get Segment/Metric/Element?

```json
	{
		"id":"visits",
		"name":"Visits",
		"type":"number",
		"decimals":0,
		"formula":null
	},
	{
		"id":"cm300000899_557f46ece4b0d23197c999ca",
		"name":"Gallery Interaction Rate",
		"type":"decimal",
		"decimals":1,
		"formula":null
	}
```

**Comment by dancingcactus** [comment]
That is exactly the solution I am accepting. The request you are running would just have one small change. 

```python
report = suite.report.nocache().element('page').metric('visits').range(dateFrom, dateTo).filter(element='evar54',selected=[url])
```
The down side like you pointed out is you couldn't use the friendly names when the nocache() flag is present (especially for Calculated Metrics and Segments). I really like that solution. Happy to help code it if you want.

**Comment by dancingcactus** [comment]
@adibbehjat I had a few minutes today and was able to get this put in. I have created a pull request. Have a look and let me know what you think. It is Pull Request #38 If you think it solves your use-case let me know and I will merge it in.

**Comment by adibbehjat** [comment]
Sorry for being MIA. Things at Apple go crazy few days before events. Had to work on other projects and didn't have much bandwidth to work on the solution. Thank you again for the help!

**Comment by dancingcactus** [comment]
Haha. No worries. Totally understand. I had a hour to kill and this seemed like a fun project. Glad I could help.

**Pull request merged**
